config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name LIKE ?", "%#{params[:query]}%")
    else
      @flats = Flat.all
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    # @flat = Flat.find(params[:id])
    @markers = [{
        lat: @flat.latitude,
        lng: @flat.longitude
        # info_window: render_to_string(partial: "info_window", locals: {flat: flat})
      }]
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :picture_url %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Edit flat</h1>
        <div class="mt-3">
          <%= render "form", flat: @flat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="main container">

  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @flats.count %> flats out of our <%= Flat.count %> on our website.</p>
      <% else %>
        <p>All <%= Flat.count %> flats:</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4">
        <div class="flat-card">
          <div class="flat-card-image" style="background-image: url('<%= flat.picture_url %>')"></div>
          <div class="flat-card-content">
            <div class="flat-card-title">
              <h4><%= flat.name %></h4>
            </div>
            <p><%= flat.address %></p>
            <div class="flex">
              <div class="flex align-items-center">
                <i class="fa-solid fa-people-line"></i>
                <span><%= flat.number_of_guests %></span>
              </div>
              <div class="flex align-items-center ms-3">
                <i class="fa-solid fa-euro-sign"></i>
                <span><%= flat.price_per_night %></span>
              </div>
            </div>
          </div>
          <div class="flat-card-actions">
            <%= link_to "More info", flat_path(flat) %>
            <%= link_to "Edit", edit_flat_path(flat), class: "ms-3 text-warning" %>
            <%= link_to "Remove", flat_path(flat),
                data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                class: "ms-3 text-danger"
            %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new Flat</h1>
        <div class="mt-3">
          <%= render "form", flat: @flat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('<%= @flat.picture_url %>')"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>

        <div style="width: 100%; height: 600px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>

      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-text" id="start-date-label">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="start-date" aria-describedby="start-date-label">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-text" id="end-date-label">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="end-date" aria-describedby="start-date-label">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <%= @flat.number_of_guests %> people
          </div>
          <div class="flex ms-3">
            <%= @flat.price_per_night %>€
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fa-brands fa-facebook-square me-2"></i>
            <i class="fa-brands fa-twitter-square me-2"></i>
            <i class="fa-brands fa-pinterest-square me-2"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <the-script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></the-script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Simple Airbnb", root_path, class: "navbar-brand" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="ms-auto flex">
        <form class="flex my-2 my-lg-0">
          <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search" value="<%= params[:query] %>">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary my-2 my-sm-0 ms-2" %>
      </div>
    </div>
  </div>
</nav>